### ISSUE TITLE
nifty.py

### ISSUE THREAD

**Issue by thilak46kumar** [andrew-geeks/Webscrapping-data-from-stock-market-using-python-BeautifulSoup#1]
hey andrew ,in the current file(nifty.py)value = soup.find(class_="lastprice").get_text() ,i got an error called AttributeError: 'NoneType' object has no attribute 'get_text'

**Comment by andrew-geeks** [comment]
actually the code is now depreciated. I have updated the code for NodeJS and soon for python will be done. Sorry for the inconvenience caused. 
[https://github.com/andrew-geeks/stock-market-scrapping-nodejs]()
